const { expect, test } = require('@playwright/test')
const { completeOnboarding, liveToken } = require('./helpers.cjs')

test('mobile PAPER header, search, trade panes, and chart controls stay usable',async({page,request})=>{
  const token=await liveToken(request)
  await page.goto('/spot?mint='+encodeURIComponent(token.mint),{waitUntil:'domcontentloaded'})
  await completeOnboarding(page,'mobile')

  const primaryNav=page.getByRole('navigation',{name:'Primary navigation'})
  await expect(primaryNav.getByRole('link',{name:'Spot',exact:true})).toBeVisible()
  await expect(primaryNav.getByRole('link',{name:'Pulse',exact:true})).toBeVisible()
  await expect(page.locator('.ax-profile-entry')).toBeVisible()
  const search=page.getByLabel('Search tokens')
  await expect(search).toBeVisible()
  const s=await search.boundingBox(),p=await page.locator('.ax-profile-entry').boundingBox()
  expect(s&&p).toBeTruthy()
  const overlap=!(s.x+s.width<=p.x||p.x+p.width<=s.x||s.y+s.height<=p.y||p.y+p.height<=s.y)
  expect(overlap).toBeFalsy()

  const terminal=page.locator('main.parts23-terminal')
  for(const pane of ['Chart','Trade','Positions','Info']){
    await page.getByRole('button',{name:pane,exact:true}).click()
    await expect(terminal).toHaveAttribute('data-mobile-pane',pane.toLowerCase())
  }

  await page.getByRole('button',{name:'Chart',exact:true}).click()
  const chart=page.locator('.lw-chart-canvas')
  await expect(chart).toBeVisible()
  const picker=page.locator('.tf-picker-button')
  await expect(picker).toBeVisible()
  for(const [label,expected] of [['5 minutes','5 minutes'],['1 minute','1 minute']]){
    await picker.click()
    await page.getByRole('menuitem',{name:label,exact:true}).click()
    await expect(picker).toContainText(expected)
    await expect(chart).toBeVisible()
  }

  await page.getByRole('button',{name:'Trade',exact:true}).click()
  await expect(page.getByText('INSTANT BUY',{exact:true})).toBeVisible()
  await expect(page.locator('.instant-buy-preset')).toHaveCount(4)
  await expect(page.locator('.percentage-sell-button')).toHaveCount(4)
})

test('mobile Pulse keeps all five boards readable',async({page})=>{
  await page.goto('/pulse',{waitUntil:'domcontentloaded'})
  await completeOnboarding(page,'pulse')
  for(const title of ['New Pairs','Final Stretch','Migrated','Trending','High Volume'])await expect(page.locator('.pulse-board-head').filter({hasText:title})).toHaveCount(1)
  await expect(page.locator('.pulse-five-grid .pulse-board-column')).toHaveCount(5)
  const overflow=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth:window.innerWidth}))
  expect(overflow.scrollWidth).toBeLessThanOrEqual(overflow.innerWidth+2)
  await expect(page.getByRole('button',{name:/Filters/})).toBeVisible()
  const dock=page.locator('.restored-feature-dock')
  await expect(dock).toBeVisible()
  const pulseDockLink=dock.getByRole('link',{name:'Pulse',exact:true})
  await expect(pulseDockLink).toBeVisible()
  await expect(pulseDockLink).toHaveClass(/active/)
  await expect(dock.getByRole('link',{name:'Spot',exact:true})).toBeVisible()
  await expect(dock.getByRole('link',{name:'Profile',exact:true})).toBeVisible()
  await expect(dock.getByRole('link',{name:'Markets',exact:true})).toBeVisible()
  const more=page.getByRole('button',{name:'More',exact:true})
  await expect(more).toBeVisible()
  await more.click()
  const moreMenu=page.getByRole('menu',{name:'More PAPER tools'})
  await expect(moreMenu).toBeVisible()
  await expect(moreMenu.getByRole('menuitem',{name:'Scanner',exact:true})).toBeVisible()
  await expect(moreMenu.getByRole('menuitem',{name:'Charity',exact:true})).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(moreMenu).toHaveCount(0)
  const refresh=page.getByRole('button',{name:'Refresh',exact:true})
  await refresh.click()
  await expect(page.locator('.terminal-toast')).toContainText(/Pulse refresh(ed| failed)/,{timeout:20000})
  await expect(dock).toBeVisible()
})
