'use client'

import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import Link from 'next/link'
import { ExternalLink, Globe2, Search, Star, Twitter } from 'lucide-react'
import AppHeader from '@/components/AppHeader'
import BottomDock from '@/components/BottomDock'
import { createClient } from '@/lib/supabase/client'
import { ensurePaperUser } from '@/lib/paper-session'
import type { MarketToken } from '@/lib/types'

type Chain='base'|'ethereum'
type SavedRef={chain_id:string;address:string}
const evm=/^0x[a-fA-F0-9]{40}$/
const money=(n:number)=>!Number.isFinite(n)?'—':n>=1e9?`$${(n/1e9).toFixed(2)}B`:n>=1e6?`$${(n/1e6).toFixed(2)}M`:n>=1e3?`$${(n/1e3).toFixed(1)}K`:`$${n.toFixed(n<1?6:2)}`
const short=(s:string)=>`${s.slice(0,6)}…${s.slice(-4)}`
const chainLabel:Record<Chain,string>={base:'Base',ethereum:'Ethereum'}

export default function ChainsPage(){
  const supabase=useMemo(()=>{try{return createClient()}catch{return null}},[]),busy=useRef(false)
  const [chain,setChain]=useState<Chain>('base'),[tokens,setTokens]=useState<MarketToken[]>([]),[query,setQuery]=useState(''),[source,setSource]=useState(''),[status,setStatus]=useState<'LIVE'|'DEGRADED'>('DEGRADED'),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[searching,setSearching]=useState(false),[saved,setSaved]=useState<Set<string>>(new Set())
  async function load(){if(busy.current||document.hidden)return;busy.current=true;try{const r=await fetch(`/api/market/chain/${chain}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||`feed ${r.status}`);const list=(j.tokens||[]) as MarketToken[];if(list.length)setTokens(list);setSource(j.source||'market feed');setStatus(j.stale?'DEGRADED':'LIVE');setNotice(j.warning||(!list.length?'No live markets are available right now. PAPER is retrying automatically.':''))}catch(e){setStatus('DEGRADED');setNotice((e instanceof Error?e.message:'Multi-chain feed unavailable')+' · Retrying automatically.')}finally{setLoading(false);busy.current=false}}
  useEffect(()=>{const start=window.setTimeout(()=>{setTokens([]);setLoading(true);void load()},0);const id=window.setInterval(()=>void load(),15000);return()=>{clearTimeout(start);clearInterval(id)}},[chain])
  useEffect(()=>{if(!supabase)return;let alive=true;const start=window.setTimeout(()=>void(async()=>{try{const user=await ensurePaperUser(supabase),{data}=await supabase.from('token_watchlist').select('chain_id,address').eq('user_id',user.id),refs=(data||[]) as SavedRef[];if(alive)setSaved(new Set(refs.map(r=>`${r.chain_id}:${String(r.address).toLowerCase()}`)))}catch{}})(),0);return()=>{alive=false;clearTimeout(start)}},[supabase])
  async function directLookup(e:FormEvent){e.preventDefault();const q=query.trim();if(!q)return;if(!evm.test(q)){setNotice('Paste a 0x contract address for direct lookup, or use ticker/name filtering below.');return}setSearching(true);try{const r=await fetch(`/api/market/chain/${chain}/token/${q}`,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.token)throw new Error(j.error||'Token not found');const token=j.token as MarketToken;setTokens(cur=>[token,...cur.filter(t=>t.mint.toLowerCase()!==token.mint.toLowerCase())]);setNotice(`Found ${token.symbol} on ${chainLabel[chain]}.`)}catch(err){setNotice(err instanceof Error?err.message:'Contract lookup failed')}finally{setSearching(false)}}
  async function watch(t:MarketToken){if(!supabase)return;try{const user=await ensurePaperUser(supabase),key=`${chain}:${t.mint.toLowerCase()}`;if(saved.has(key)){const {error}=await supabase.from('token_watchlist').delete().eq('user_id',user.id).eq('chain_id',chain).eq('address',t.mint);if(error)throw error;setSaved(cur=>{const n=new Set(cur);n.delete(key);return n})}else{const {error}=await supabase.from('token_watchlist').upsert({user_id:user.id,chain_id:chain,address:t.mint,symbol:t.symbol,name:t.name,image_url:t.image||null},{onConflict:'user_id,chain_id,address'});if(error)throw error;setSaved(cur=>new Set(cur).add(key))}}catch(err){setNotice(err instanceof Error?err.message:'Watchlist update failed')}}
  const rows=useMemo(()=>{const q=query.trim().toLowerCase();const list=!q||evm.test(query.trim())?tokens:tokens.filter(t=>t.symbol.toLowerCase().includes(q)||t.name.toLowerCase().includes(q));return [...list].sort((a,b)=>(Number(b.volume5m||0)+Number(b.liquidityUsd||0)*.1)-(Number(a.volume5m||0)+Number(a.liquidityUsd||0)*.1)).slice(0,60)},[tokens,query])
  return <div className="ax-app"><AppHeader active="chains"/><main className="terminal-page chains-page"><div className="terminal-page-inner">
    <div className="final-page-hero"><div><div className="terminal-eyebrow">MULTI-CHAIN MARKET WATCH · REAL DEX DATA</div><h1>Base + Ethereum</h1><p className="terminal-lead">Live token discovery outside Solana. These markets are read-only in PAPER for now; simulated PAPER execution remains on the Solana engine.</p></div><Link className="watchlist-link" href="/watchlist"><Star size={14}/> Watchlist</Link></div>
    <section className="chain-toolbar"><div className="chain-tabs"><Link href="/spot">Solana</Link><button className={chain==='base'?'active':''} onClick={()=>setChain('base')}>Base</button><button className={chain==='ethereum'?'active':''} onClick={()=>setChain('ethereum')}>Ethereum</button></div><form onSubmit={directLookup}><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${chainLabel[chain]} ticker/name or paste 0x CA…`}/><button disabled={searching}>{searching?'…':'Find'}</button></form><span className={`chain-status ${status.toLowerCase()}`}><i/>{status}</span></section>
    {notice&&<div className={status==='LIVE'?'terminal-toast inline':'terminal-error'}>{notice}</div>}<div className="chain-paper-note"><b>WATCH MODE:</b> Base/Ethereum rows use real public market data and external market links. PAPER buy/sell is intentionally disabled until the accounting model stores chain-aware positions.</div>
    <section className="chain-market-table"><div className="chain-market-head"><span>Token</span><span>Price</span><span>5m</span><span>Market Cap</span><span>Liquidity</span><span>5m Volume</span><span>5m Buys/Sells</span><span>Social</span><span>Watch</span></div>{loading&&!rows.length&&Array.from({length:8}).map((_,i)=><div className="chain-skeleton" key={i}><span/><span/><span/><span/></div>)}{!loading&&!rows.length&&<div className="portfolio-empty">No live markets are available right now. PAPER is retrying automatically. <button onClick={()=>void load()}>Retry now</button></div>}{rows.map(t=>{const change=Number(t.priceChange5m||0),key=`${chain}:${t.mint.toLowerCase()}`,market=t.pairUrl||t.buyUrl;return <div className="chain-market-row" key={`${chain}:${t.mint}`}><span className="chain-token"><span className="pair-avatar-terminal">{t.image?<img src={t.image} alt=""/>:<b>{t.symbol.slice(0,2)}</b>}</span><span><b>${t.symbol}</b><small>{t.name} · {String(t.dexId||'DEX')}</small><code>{short(t.mint)}</code></span></span><strong>{money(t.priceUsd)}</strong><strong className={change>=0?'gain':'loss'}>{change>=0?'+':''}{change.toFixed(2)}%</strong><span>{money(t.marketCap)}</span><span>{money(t.liquidityUsd)}</span><span>{money(Number(t.volume5m||0))}</span><span><b className="gain">{Number(t.buys5m||0)}</b> / <b className="loss">{Number(t.sells5m||0)}</b></span><span className="chain-socials">{t.website&&<a href={t.website} target="_blank" rel="noreferrer" title="Website"><Globe2 size={13}/></a>}{t.twitter&&<a href={t.twitter} target="_blank" rel="noreferrer" title="X"><Twitter size={13}/></a>}<a href={`https://x.com/search?q=${encodeURIComponent(t.mint)}`} target="_blank" rel="noreferrer" title="Search CA on X"><Search size={13}/></a>{market&&<a href={market} target="_blank" rel="noreferrer" title="Open market"><ExternalLink size={13}/></a>}</span><button className={saved.has(key)?'watch-star active':'watch-star'} onClick={()=>void watch(t)} title={saved.has(key)?'Remove from watchlist':'Add to watchlist'}><Star size={14} fill={saved.has(key)?'currentColor':'none'}/></button></div>})}</section>
    <div className="terminal-source"><i/>{status} · {source||'waiting for feed'} · {chainLabel[chain]} public DEX market data · no real-money execution</div>
  </div></main><BottomDock active="chains"/></div>
}
