import Link from 'next/link'

export default function LegalPage(){
  return <main style={{minHeight:'100vh',background:'#07080c',color:'#f5f6f8',padding:'48px 20px',fontFamily:'Inter,ui-sans-serif,system-ui'}}><div style={{maxWidth:900,margin:'0 auto'}}>
    <Link href="/" style={{color:'#6f86ff',textDecoration:'none'}}>← Back to PAPER</Link>
    <h1 style={{fontSize:34,margin:'24px 0 8px'}}>PAPER Legal & Risk Documents</h1>
    <p style={{color:'#9198aa',lineHeight:1.7}}>Version 1 · PAPER is a simulated trading product. These documents cover PAPER-only use. Real-money prizes remain disabled until separate official rules and legal review are complete.</p>

    <section id="terms" style={{marginTop:44}}><h2>Terms of Service — v1</h2><p style={{color:'#b8becc',lineHeight:1.8}}>PAPER provides simulated trading tools using public market information. PAPER balances, positions, fills, points, rankings, and portfolio values are simulated records and are not deposits, brokerage assets, or claims on real cryptocurrency. PAPER does not hold user trading funds and PAPER trade controls do not submit blockchain transactions.</p><p style={{color:'#b8becc',lineHeight:1.8}}>Users must not attempt to exploit bugs, manipulate competitions, automate abusive traffic, create duplicate identities for rewards, or interfere with market-data services. PAPER may pause trading, correct clearly erroneous simulated fills caused by a verified product incident, suspend abusive accounts, and change features while the service is in development. Any future competition involving real value will use separate published official rules.</p></section>

    <section id="privacy" style={{marginTop:44}}><h2>Privacy Policy — v1</h2><p style={{color:'#b8becc',lineHeight:1.8}}>PAPER stores the information needed to run an account, including profile details you provide, simulated trade history, positions, points, moderation records, and security signals used to protect the service. Anonymous accounts may also use limited IP/device risk signals for rate limiting and abuse review. Recovery email, payout information, IP addresses, and device signals are not public profile information.</p><p style={{color:'#b8becc',lineHeight:1.8}}>An anonymous account cannot be recovered after browser storage is cleared or the user changes devices unless a recovery method has been linked. PAPER will keep data only as needed for product operation, security, support, legal obligations, and competition integrity. More detailed retention and deletion controls will be published before a public rewards/payout launch.</p></section>

    <section id="risk" style={{marginTop:44}}><h2>Risk Disclosure — v1</h2><p style={{color:'#b8becc',lineHeight:1.8}}>Memecoin markets are highly volatile and can lose most or all real-world value quickly. PAPER is educational/simulated software, not investment advice. A profitable PAPER result does not mean the same trade could be executed for the same price, liquidity, impact, latency, or fee on-chain.</p><p style={{color:'#b8becc',lineHeight:1.8}}>PAPER uses available market data and execution models to estimate fills. When the model is not protocol-aware, fills are labeled estimated. If market data is stale or unavailable, PAPER may pause new simulated orders. External market links leave PAPER and may involve real funds; PAPER does not execute those transactions.</p></section>

    <div style={{marginTop:52,paddingTop:22,borderTop:'1px solid #222633',color:'#737b8c',fontSize:13}}>Competition and payout rules are intentionally not active in v1. No real cash-prize program is promised by this page.</div>
  </div></main>
}
