'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { BookOpen, Save, Trash2 } from 'lucide-react'
import AppHeader from '@/components/AppHeader'
import BottomDock from '@/components/BottomDock'
import { createClient } from '@/lib/supabase/client'
import { ensurePaperUser } from '@/lib/paper-session'

type Row={id:string;trade_id:string|null;token_address:string;token_symbol:string|null;strategy_tag:string|null;entry_reason:string|null;notes:string|null;rating:number|null;created_at:string}
type Trade={id:string;action:string;ts:string;tokens:{mint_address:string;ticker:string|null}|null}
const tags=['breakout','dip buy','new launch','momentum','reversal','scalp','other']

export default function JournalPage(){
 const supabase=useMemo(()=>{try{return createClient()}catch{return null}},[])
 const [rows,setRows]=useState<Row[]>([]),[trades,setTrades]=useState<Trade[]>([]),[tradeId,setTradeId]=useState(''),[tag,setTag]=useState('new launch'),[reason,setReason]=useState(''),[notes,setNotes]=useState(''),[rating,setRating]=useState(3),[error,setError]=useState('')
 async function load(){if(!supabase)return;try{const u=await ensurePaperUser(supabase);const [j,t]=await Promise.all([supabase.from('paper_trade_journal').select('*').eq('user_id',u.id).order('created_at',{ascending:false}),supabase.from('paper_trades').select('id,action,ts,tokens(mint_address,ticker)').eq('user_id',u.id).order('ts',{ascending:false}).limit(100)]);if(j.error)throw j.error;if(t.error)throw t.error;setRows((j.data||[]) as Row[]);setTrades((t.data||[]) as unknown as Trade[])}catch(e){setError(e instanceof Error?e.message:'Journal unavailable')}}
 useEffect(()=>{void load()},[])
 async function save(e:FormEvent){e.preventDefault();if(!supabase)return;const trade=trades.find(t=>t.id===tradeId);if(!trade?.tokens?.mint_address){setError('Choose a recorded PAPER trade.');return}try{const u=await ensurePaperUser(supabase);const {error}=await supabase.from('paper_trade_journal').insert({user_id:u.id,trade_id:trade.id,token_address:trade.tokens.mint_address,token_symbol:trade.tokens.ticker,strategy_tag:tag,entry_reason:reason.trim()||null,notes:notes.trim()||null,rating});if(error)throw error;setReason('');setNotes('');await load();setError('')}catch(e){setError(e instanceof Error?e.message:'Could not save journal entry')}}
 async function remove(id:string){if(!supabase)return;await supabase.from('paper_trade_journal').delete().eq('id',id);await load()}
 const stats=useMemo(()=>tags.map(t=>{const list=rows.filter(r=>r.strategy_tag===t);return{tag:t,count:list.length,rating:list.length?list.reduce((s,r)=>s+Number(r.rating||0),0)/list.length:0}}).filter(x=>x.count),[rows])
 return <div className="ax-app"><AppHeader active="portfolio"/><main className="terminal-page"><div className="terminal-page-inner"><div className="final-page-hero"><div><div className="terminal-eyebrow">TRADING JOURNAL</div><h1>Record why you took the trade.</h1><p className="terminal-lead">Attach a strategy, entry thesis, notes and a self-review score to your server-recorded PAPER fills.</p></div><BookOpen size={28}/></div>{error&&<div className="error-card">{error}</div>}<section className="journal-layout"><form className="journal-form" onSubmit={save}><label>Recorded PAPER trade<select value={tradeId} onChange={e=>setTradeId(e.target.value)}><option value="">Choose trade…</option>{trades.map(t=><option key={t.id} value={t.id}>{new Date(t.ts).toLocaleString()} · {t.action.toUpperCase()} · {'$'+(t.tokens?.ticker||'TOKEN')}</option>)}</select></label><label>Strategy<select value={tag} onChange={e=>setTag(e.target.value)}>{tags.map(t=><option key={t}>{t}</option>)}</select></label><label>Why did you enter?<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500}/></label><label>Post-trade notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1000}/></label><label>Execution score <input type="range" min="1" max="5" value={rating} onChange={e=>setRating(Number(e.target.value))}/><b>{rating}/5</b></label><button><Save size={13}/> Save journal entry</button></form><aside className="journal-stats"><div className="panel-title"><b>STRATEGY REVIEW</b><span>{rows.length} notes</span></div>{stats.length?stats.map(s=><div className="journal-stat" key={s.tag}><b>{s.tag}</b><span>{s.count} entries</span><strong>{s.rating.toFixed(1)}/5 avg self-score</strong></div>):<div className="empty-card">Journal entries will build your strategy review here.</div>}</aside></section><section className="journal-list">{rows.map(r=><article key={r.id}><button onClick={()=>void remove(r.id)}><Trash2 size={12}/></button><div><b>{'$'+(r.token_symbol||'TOKEN')} · {r.strategy_tag||'untagged'}</b><small>{new Date(r.created_at).toLocaleString()} · self-score {r.rating||'—'}/5</small></div>{r.entry_reason&&<p><strong>Entry:</strong> {r.entry_reason}</p>}{r.notes&&<p><strong>Review:</strong> {r.notes}</p>}</article>)}</section></div></main><BottomDock active="portfolio"/></div>
}
