'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { Gift, HeartHandshake, Share2, Sparkles, Trophy } from 'lucide-react'
import AppHeader from '@/components/AppHeader'
import BottomDock from '@/components/BottomDock'
import { createClient } from '@/lib/supabase/client'
import { ensurePaperUser } from '@/lib/paper-session'

type Total={user_id:string;points:number;qualifying_trades:number;last_earned_at:string|null;profiles?:{username:string|null;display_name:string|null;avatar_url:string|null;avatar_emoji:string|null}|null}
type Event={id:string;event_type:string;points:number;created_at:string}
const tiers=[{name:'Scout',min:0},{name:'Grinder',min:100},{name:'Degen',min:500},{name:'Alpha',min:1500},{name:'Legend',min:5000}]
function tierFor(points:number){let current=tiers[0];for(const tier of tiers)if(points>=tier.min)current=tier;return current}
function nextTier(points:number){return tiers.find(t=>t.min>points)||null}

export default function RewardsPage(){
  const supabase=useMemo(()=>{try{return createClient()}catch{return null}},[])
  const [total,setTotal]=useState<Total|null>(null),[events,setEvents]=useState<Event[]>([]),[leaders,setLeaders]=useState<Total[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true)
  useEffect(()=>{if(!supabase)return;let alive=true;async function load(){try{const user=await ensurePaperUser(supabase);const [{data:t,error:te},{data:e,error:ee},{data:l,error:le}]=await Promise.all([supabase.from('paper_reward_totals').select('user_id,points,qualifying_trades,last_earned_at').eq('user_id',user.id).maybeSingle(),supabase.from('paper_reward_events').select('id,event_type,points,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50),supabase.from('paper_reward_totals').select('user_id,points,qualifying_trades,last_earned_at,profiles(username,display_name,avatar_url,avatar_emoji)').order('points',{ascending:false}).limit(20)]);if(te)throw te;if(ee)throw ee;if(le)throw le;if(!alive)return;setTotal((t as Total|null)||{user_id:user.id,points:0,qualifying_trades:0,last_earned_at:null});setEvents((e||[]) as Event[]);setLeaders((l||[]) as unknown as Total[]);setError('')}catch(err){if(alive)setError(err instanceof Error?err.message:'Rewards unavailable')}finally{if(alive)setLoading(false)}}void load();const id=window.setInterval(()=>{if(!document.hidden)void load()},12000);return()=>{alive=false;clearInterval(id)}},[supabase])
  const points=Number(total?.points||0),tier=tierFor(points),next=nextTier(points),progress=next?Math.max(0,Math.min(100,(points-tier.min)/(next.min-tier.min)*100)):100
  function share(){const text=`I have ${points.toLocaleString()} PAPER Points and ${Number(total?.qualifying_trades||0)} simulated fills on PAPER. Real market data. PAPER trading only.`;window.open(`https://x.com/intent/tweet?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}
  return <div className="ax-app"><AppHeader active="rewards"/><main className="terminal-page rewards-page"><div className="terminal-page-inner">
    <div className="final-page-hero"><div><div className="terminal-eyebrow">PAPER REWARDS · STATUS POINTS ONLY</div><h1>Rewards</h1><p className="terminal-lead">Every server-recorded USD-mode PAPER fill earns 10 PAPER Points. Points track participation and status; they are not cash, crypto, or a promise of a prize.</p></div><button className="final-share-button" onClick={share}><Share2 size={14}/> Share on X</button></div>{error&&<div className="error-card">{error}</div>}
    <section className="reward-hero-grid"><div className="reward-score-card"><small>PAPER POINTS</small><b>{loading?'…':points.toLocaleString()}</b><span><Sparkles size={13}/>{tier.name} tier</span><div className="reward-progress"><i style={{width:`${progress}%`}}/></div><p>{next?`${Math.max(0,next.min-points).toLocaleString()} points to ${next.name}`:'Top tier unlocked'}</p></div><div className="reward-stat"><small>QUALIFYING FILLS</small><b>{Number(total?.qualifying_trades||0).toLocaleString()}</b><span>10 points per server-recorded PAPER fill</span></div><div className="reward-stat"><small>REAL PRIZES</small><b>OFF</b><span>Disabled pending official rules and compliance</span></div><div className="reward-stat"><small>LAST EARNED</small><b>{total?.last_earned_at?new Date(total.last_earned_at).toLocaleDateString():'—'}</b><span>{total?.last_earned_at?new Date(total.last_earned_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'No points earned yet'}</span></div></section>
    <section className="reward-info-grid"><article className="reward-panel"><div className="panel-title"><b>HOW POINTS WORK</b><Gift size={15}/></div><div className="reward-rules"><div><b>+10</b><span>Each completed USD-mode PAPER buy or sell recorded by the server</span></div><div><b>0</b><span>Page views, refreshes, failed orders, or idempotent replays</span></div><div><b>STATUS</b><span>Points unlock visible tiers only. No monetary value.</span></div></div></article><article className="reward-panel charity"><div className="panel-title"><b>GIVEAWAY MATCH PLEDGE</b><HeartHandshake size={15}/></div><p>If official PAPER giveaways are activated later, the stated policy is a dollar-for-dollar charity match — for example, a $1,000 giveaway would be paired with a $1,000 charity donation.</p><strong>Giveaways and matching are not active yet.</strong><Link href="/coin">View community coin & charity policy</Link></article></section>
    <section className="reward-board"><div className="panel-title"><b>POINTS LEADERBOARD</b><Link href="/leaderboards">Full leaderboards →</Link></div><div className="reward-board-head"><span>#</span><span>Trader</span><span>Points</span><span>Fills</span></div>{!leaders.length&&!loading&&<div className="portfolio-empty">No reward activity yet.</div>}{leaders.map((row,i)=>{const p=row.profiles,display=p?.display_name||p?.username||'Paper Trader';return <Link href={`/trader/${row.user_id}`} className="reward-board-row" key={row.user_id}><b>{i+1}</b><span className="leader-trader">{p?.avatar_url?<img src={p.avatar_url} alt=""/>:<span className="leader-emoji">{p?.avatar_emoji||'◢'}</span>}<span><strong>{display}</strong><small>@{p?.username||'paper_trader'}</small></span></span><strong>{Number(row.points||0).toLocaleString()}</strong><span>{Number(row.qualifying_trades||0).toLocaleString()}</span></Link>})}</section>
    <section className="reward-panel"><div className="panel-title"><b>YOUR RECENT POINT EVENTS</b><Trophy size={15}/></div>{!events.length?<div className="portfolio-empty">Complete a PAPER trade to earn your first points.</div>:<div className="reward-event-list">{events.map(e=><div key={e.id}><span>{new Date(e.created_at).toLocaleString()}</span><b>{e.event_type.replaceAll('_',' ')}</b><strong>+{e.points}</strong></div>)}</div>}</section>
  </div></main><BottomDock active="rewards"/></div>
}
