'use client'

import { FormEvent, startTransition, useEffect, useMemo, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Eye, EyeOff, Filter, Globe2, Search, Settings2, Zap } from 'lucide-react'
import AppHeader from '@/components/AppHeader'
import BottomDock from '@/components/BottomDock'
import FastPulseStrip from '@/components/FastPulseStrip'
import MarketFilterDrawer from '@/components/MarketFilterDrawer'
import MarketMiniChart from '@/components/MarketMiniChart'
import { createClient } from '@/lib/supabase/client'
import { ensurePaperUser } from '@/lib/paper-session'
import { activeFilterCount, defaultMarketFilters, tokenMatchesFilters, type MarketFilters } from '@/lib/market-filters'
import { useInstantMode } from '@/lib/use-instant-mode'
import type { MarketToken } from '@/lib/types'

const money=(n:number)=>!Number.isFinite(n)?'—':n>=1e9?`$${(n/1e9).toFixed(2)}B`:n>=1e6?`$${(n/1e6).toFixed(2)}M`:n>=1e3?`$${(n/1e3).toFixed(1)}K`:`$${n.toFixed(n<1?6:2)}`
const age=(ms?:number)=>{if(!ms)return'—';const s=Math.floor(Math.max(0,Date.now()-ms)/1000);if(s<60)return`${s}s`;const m=Math.floor(s/60);if(m<60)return`${m}m`;const h=Math.floor(m/60);return h<24?`${h}h`:`${Math.floor(h/24)}d`}
const ageMs=(ms?:number)=>ms?Math.max(0,Date.now()-ms):Number.MAX_SAFE_INTEGER
const isMint=(s:string)=>/^[1-9A-HJ-NP-Za-km-z]{32,60}$/.test(s.trim())
type TabMode='top'|'trending'|'radar'
type VenueMode='all'|'pump'|'raydium'|'meteora'|'other'
type Timeframe='1m'|'5m'|'1h'|'6h'|'24h'
const presets=[{id:'P1',value:.1},{id:'P2',value:.5},{id:'P3',value:1}]
const changeFor=(t:MarketToken,tf:Timeframe)=>Number(tf==='1m'?t.priceChange1m:tf==='5m'?t.priceChange5m:tf==='1h'?t.priceChange1h:tf==='6h'?t.priceChange6h:t.priceChange24h)||0
const volumeFor=(t:MarketToken,tf:Timeframe)=>Number(tf==='1m'?t.volume1m:tf==='5m'?t.volume5m:tf==='1h'?t.volume1h:tf==='6h'?t.volume6h:t.volume24h)||0
const buysFor=(t:MarketToken,tf:Timeframe)=>Number(tf==='1m'?t.buys1m:tf==='5m'?t.buys5m:tf==='1h'?t.buys1h:tf==='6h'?t.buys6h:t.buys24h)||0
const sellsFor=(t:MarketToken,tf:Timeframe)=>Number(tf==='1m'?t.sells1m:tf==='5m'?t.sells5m:tf==='1h'?t.sells1h:tf==='6h'?t.sells6h:t.sells24h)||0
const hotScore=(t:MarketToken)=>Number(t.volume1m||0)*7+Number(t.volume5m||0)*2+(Number(t.buys1m||0)+Number(t.sells1m||0))*900+(Number(t.buys5m||0)+Number(t.sells5m||0))*90+Math.abs(Number(t.priceChange1m||0))*9000+Math.abs(Number(t.priceChange5m||0))*2000+Math.min(Number(t.liquidityUsd||0),250000)*.03
const feedSignature=(tokens:MarketToken[])=>tokens.map(t=>`${t.mint}:${Number(t.priceUsd||0).toPrecision(8)}:${Math.round(Number(t.volume5m||0))}:${Number(t.buys5m||0)}:${Number(t.sells5m||0)}`).join('|')

export default function DiscoverHome(){
  const [tokens,setTokens]=useState<MarketToken[]>([]),[views,setViews]=useState<Record<string,number>>({}),[tab,setTab]=useState<TabMode>('top'),[venue,setVenue]=useState<VenueMode>('all'),[time,setTime]=useState<Timeframe>('5m'),[query,setQuery]=useState(''),[searching,setSearching]=useState(false),[buySize,setBuySize]=useState(.1),[presetId,setPresetId]=useState('P1'),[buying,setBuying]=useState(''),[notice,setNotice]=useState(''),[feedError,setFeedError]=useState(''),[loading,setLoading]=useState(true),[source,setSource]=useState(''),[dataStatus,setDataStatus]=useState<'LIVE'|'DEGRADED'|'STALE'>('DEGRADED'),[settingsOpen,setSettingsOpen]=useState(false),[compactRows,setCompactRows]=useState(false),[hideLowLiquidity,setHideLowLiquidity]=useState(false),[filters,setFilters]=useState<MarketFilters>(defaultMarketFilters),[filterOpen,setFilterOpen]=useState(false)
  const loadBusy=useRef(false),lastViewsAt=useRef(0),lastFeedSignature=useRef(''),supabase=useMemo(()=>{try{return createClient()}catch{return null}},[]),router=useRouter(),[instantMode]=useInstantMode(),filterCount=activeFilterCount(filters)

  async function loadViews(next:MarketToken[]){if(!supabase||!next.length||Date.now()-lastViewsAt.current<20_000)return;lastViewsAt.current=Date.now();const {data}=await supabase.from('token_view_totals').select('mint_address,views').in('mint_address',next.map(t=>t.mint));if(data){const map:Record<string,number>={};for(const row of data)map[String(row.mint_address)]=Number(row.views||0);setViews(map)}}
  async function load(force=false){if(loadBusy.current)return;if(typeof document!=='undefined'&&document.hidden&&!force)return;loadBusy.current=true;try{const r=await fetch('/api/market/latest',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||`market feed ${r.status}`);const next=(j.tokens||[]) as MarketToken[];if(!next.length)throw new Error('Market feed returned zero supported tokens.');const signature=feedSignature(next);if(signature!==lastFeedSignature.current){lastFeedSignature.current=signature;startTransition(()=>setTokens(next))}setSource(j.source||'market feed');setFeedError(j.warning||'');setDataStatus(j.stale?'STALE':j.warning||j.fallback||j.live===false?'DEGRADED':'LIVE');void loadViews(next)}catch(e){setFeedError(e instanceof Error?e.message:'Live market feed unavailable');setDataStatus('DEGRADED')}finally{setLoading(false);loadBusy.current=false}}
  useEffect(()=>{void load(true);const id=window.setInterval(()=>void load(),4000),visible=()=>{if(!document.hidden)void load(true)};document.addEventListener('visibilitychange',visible);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',visible)}},[])
  useEffect(()=>{const savedId=localStorage.getItem('paper.quickBuyPreset'),savedSize=Number(localStorage.getItem('paper.quickBuySize'));if(savedId&&presets.some(p=>p.id===savedId))setPresetId(savedId);if(savedSize>0)setBuySize(savedSize);const handler=(e:Event)=>{const d=(e as CustomEvent<{id:string;value:number}>).detail;if(d){setPresetId(d.id);setBuySize(d.value)}};window.addEventListener('paper:preset',handler);return()=>window.removeEventListener('paper:preset',handler)},[])
  useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4200);return()=>clearTimeout(id)},[notice])
  function choosePreset(id:string,value:number){setPresetId(id);setBuySize(value);localStorage.setItem('paper.quickBuyPreset',id);localStorage.setItem('paper.quickBuySize',String(value))}
  async function searchMarket(e?:FormEvent){e?.preventDefault();const q=query.trim();if(!q)return;const local=tokens.find(t=>t.mint===q||t.symbol.toLowerCase()===q.toLowerCase()||t.name.toLowerCase()===q.toLowerCase());if(local){router.push(`/spot?mint=${local.mint}`);return}if(!isMint(q)){setNotice('No exact token in the live list. Paste a Solana contract address for direct lookup.');return}setSearching(true);setNotice('');try{const r=await fetch(`/api/market/token/${encodeURIComponent(q)}`,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.token)throw new Error(j.error||'Token found, but no supported active market was detected.');router.push(`/spot?mint=${j.token.mint}`)}catch(e2){setNotice(e2 instanceof Error?e2.message:'Token lookup failed')}finally{setSearching(false)}}

  const rows=useMemo(()=>{let list=[...tokens].filter(t=>tokenMatchesFilters(t,filters)),q=query.trim().toLowerCase();if(venue==='pump')list=list.filter(t=>/pump/i.test(t.dexId||''));if(venue==='raydium')list=list.filter(t=>/raydium/i.test(t.dexId||''));if(venue==='meteora')list=list.filter(t=>/meteora/i.test(t.dexId||''));if(venue==='other')list=list.filter(t=>!/(pump|raydium|meteora)/i.test(t.dexId||''));if(hideLowLiquidity)list=list.filter(t=>t.liquidityUsd>=10000);if(q&&!isMint(q))list=list.filter(t=>t.symbol.toLowerCase().includes(q)||t.name.toLowerCase().includes(q));if(tab==='top')list.sort((a,b)=>hotScore(b)-hotScore(a));if(tab==='trending')list.sort((a,b)=>(volumeFor(b,time)+(buysFor(b,time)+sellsFor(b,time))*100+Math.abs(changeFor(b,time))*2200)-(volumeFor(a,time)+(buysFor(a,time)+sellsFor(a,time))*100+Math.abs(changeFor(a,time))*2200));if(tab==='radar'){const fresh=list.filter(t=>ageMs(t.pairCreatedAt)<6*60*60*1000);list=(fresh.length?fresh:list).sort((a,b)=>(b.pairCreatedAt||0)-(a.pairCreatedAt||0))}return list.slice(0,40)},[tokens,query,tab,venue,hideLowLiquidity,time,filters])

  async function quickBuy(t:MarketToken){if(!supabase){setNotice('PAPER account service is unavailable.');return}try{setBuying(t.mint);setNotice('');await ensurePaperUser(supabase);const idempotencyKey=crypto.randomUUID(),{data,error}=await supabase.functions.invoke('paper-trade',{body:{mint:t.mint,side:'buy',amountSol:buySize,idempotencyKey}});if(error)throw error;if(data?.error)throw new Error(data.error);setNotice(`PAPER BUY FILLED · $${t.symbol} · ${money(Number(data.fill?.requestedAmountUsd||0))} · fee ${money(Number(data.fill?.paperFeeUsd||0))}`);window.dispatchEvent(new Event('paper:account-changed'))}catch(e){setNotice(e instanceof Error?e.message:'PAPER buy failed')}finally{setBuying('')}}
  function rowAction(t:MarketToken){if(instantMode)void quickBuy(t);else router.push(`/spot?mint=${t.mint}`)}

  const tabs:[TabMode,string][]=[['top','Top'],['trending','Trending'],['radar','Radar']],venues:{id:VenueMode;label:string;title:string}[]=[{id:'all',label:'All',title:'All Solana venues'},{id:'pump',label:'⚡',title:'Pump venues'},{id:'raydium',label:'R',title:'Raydium'},{id:'meteora',label:'M',title:'Meteora'},{id:'other',label:'◇',title:'Other Solana venues'}]
  return <div className="ax-app"><AppHeader active="discover"/><main className="market-console">
    <section className="market-topbar"><div className="market-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><form className="market-global-search" onSubmit={searchMarket}><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ticker, name or Solana CA…"/><button type="submit" disabled={searching}>{searching?'…':'Go'}</button></form><div className="market-top-spacer"/><div className="time-tabs-terminal">{(['1m','5m','1h','6h','24h'] as Timeframe[]).map(v=><button key={v} className={time===v?'active':''} onClick={()=>setTime(v)}>{v}</button>)}</div><div className="terminal-control-row"><span className={`instant-status-chip ${instantMode?'on':''}`} title="Enable Instant Mode from a token trade panel"><Zap size={11}/>{instantMode?'INSTANT ON':'INSTANT OFF'}</span><button className={`icon-control ${settingsOpen?'active':''}`} title="Display settings" onClick={()=>setSettingsOpen(v=>!v)}><Settings2 size={15}/></button><button className={`icon-control ${hideLowLiquidity?'active':''}`} title="Hide liquidity below $10K" onClick={()=>setHideLowLiquidity(v=>!v)}>{hideLowLiquidity?<EyeOff size={15}/>:<Eye size={15}/>}</button><button className={`icon-control market-filter-trigger ${filterOpen||filterCount?'active':''}`} title="Advanced market filters" onClick={()=>setFilterOpen(true)}><Filter size={15}/>{filterCount>0&&<small>{filterCount}</small>}</button><div className="quick-buy-terminal"><Zap size={12}/><span>Preset</span><input type="number" min=".01" step=".01" value={buySize} onChange={e=>{setPresetId('');setBuySize(Math.max(.01,Number(e.target.value)||.01))}}/><small>SOL</small></div><div className="preset-strip">{presets.map(p=><button key={p.id} className={presetId===p.id?'active':''} onClick={()=>choosePreset(p.id,p.value)}>{p.id}</button>)}</div></div>{settingsOpen&&<div className="terminal-settings-pop"><label><span>Compact rows</span><input type="checkbox" checked={compactRows} onChange={e=>setCompactRows(e.target.checked)}/></label><label><span>Hide liquidity &lt; $10K</span><input type="checkbox" checked={hideLowLiquidity} onChange={e=>setHideLowLiquidity(e.target.checked)}/></label><small>{instantMode?'Instant Mode is ON: row actions submit the current PAPER preset immediately.':'Instant Mode is OFF: row actions open the token trade panel first.'}</small></div>}</section>
    <MarketFilterDrawer open={filterOpen} filters={filters} onChange={setFilters} onClose={()=>setFilterOpen(false)}/>
    <FastPulseStrip tokens={tokens}/>{feedError&&<div className="terminal-error"><span><b>{dataStatus}:</b> {feedError}</span><button onClick={()=>void load(true)}>Retry</button></div>}{notice&&<div className="terminal-toast">{notice}</div>}
    <section className="market-workspace"><aside className="venue-rail">{venues.map(v=><button key={v.id} title={v.title} className={venue===v.id?'active':''} onClick={()=>setVenue(v.id)}>{v.label}</button>)}<div className="rail-divider"/><small>SOL</small></aside><div className="market-table-shell"><div className="market-table"><div className="terminal-table-head"><span>Pair Info</span><span>Chart</span><span>Market Cap</span><span>Liquidity</span><span>{time} Volume</span><span>{time} TXNS</span><span>Token Info</span><span>Action</span></div>
      {rows.map((t,index)=>{const buys=buysFor(t,time),sells=sellsFor(t,time),tx=buys+sells,buyPct=Math.round(buys/Math.max(1,tx)*100),lqRatio=t.marketCap>0?Math.min(999,(t.liquidityUsd/t.marketCap)*100):0,change=changeFor(t,time),up=change>=0,warming=time==='1m'&&!t.observed1mReady;return <div className={`terminal-table-row ${compactRows?'compact':''}`} key={t.mint}><button className="pair-cell-terminal" onClick={()=>router.push(`/spot?mint=${t.mint}`)}><span className="market-rank">{index+1}</span><div className="pair-avatar-terminal">{t.image?<img src={t.image} alt="" loading="lazy"/>:<span>{t.symbol.slice(0,2)}</span>}</div><div className="pair-copy-terminal"><div className="pair-title-terminal"><b>{t.symbol}</b><span>{t.name}</span></div><div className="pair-meta-terminal"><b>{age(t.pairCreatedAt)}</b>{t.website&&<Globe2 size={12}/>}<Eye size={12}/><span>{(views[t.mint]||0).toLocaleString()} views</span></div></div></button><div className="spark-cell-terminal"><MarketMiniChart token={t} timeframe={time}/></div><div className="metric-terminal"><b>{money(t.marketCap)}</b><span className={up?'gain':'loss'}>{warming?'warming':`${up?'+':''}${change.toFixed(2)}%`}</span></div><div className="metric-terminal"><b>{money(t.liquidityUsd)}</b><span>{lqRatio.toFixed(1)}% MC</span></div><div className="metric-terminal"><b>{warming?'warming':money(volumeFor(t,time))}</b><span>{t.dexId||'Solana'}</span></div><div className="tx-terminal"><b>{warming?'—':tx.toLocaleString()}</b><span><em className="gain">{buys}</em> / <em className="loss">{sells}</em></span></div><div className="token-info-terminal"><span className="metric-pill good">B {buyPct}%</span><span className="metric-pill bad">S {100-buyPct}%</span><span className="metric-pill">LQ {lqRatio.toFixed(1)}%</span><span className={`metric-pill ${up?'good':'bad'}`}>{warming?'1m live':`${up?'+':''}${Math.round(change)}%`}</span><span className="metric-pill blue">{String(t.dexId||'SOL').slice(0,9)}</span></div><div className="terminal-buy-wrap"><button className="terminal-buy" disabled={buying===t.mint||dataStatus==='STALE'} onClick={()=>rowAction(t)}>{buying===t.mint?'Buying…':instantMode?<>Buy {buySize}<small>SOL · INSTANT</small></>:<>Trade<small>OPEN PANEL</small></>}</button></div></div>})}
      {!rows.length&&loading&&Array.from({length:6}).map((_,i)=><div className="terminal-skeleton-row" key={i}><span/><span/><span/><span/><span/><span/></div>)}{!rows.length&&!loading&&<div className="terminal-empty">{feedError?'Live token feed is unavailable. Retrying automatically.':'No pairs match this search/filter.'}</div>}</div></div></section><div className={`terminal-source ${dataStatus!=='LIVE'?'warning':''}`}><i/>{dataStatus} · {source||'market feed'} · {rows.length}/{tokens.length} shown · real observed market metrics · PAPER trades are simulated</div>
  </main><BottomDock active="discover"/></div>
}
