'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ExternalLink, RefreshCw, Search, Star, Trash2, WalletCards } from 'lucide-react'
import AppHeader from '@/components/AppHeader'
import BottomDock from '@/components/BottomDock'
import { createClient } from '@/lib/supabase/client'
import { ensurePaperUser } from '@/lib/paper-session'

type Saved={id:string;user_id:string;address:string;label:string;notes:string|null;is_favorite:boolean;tags:string[];alert_on_activity:boolean;last_seen_signature:string|null;last_activity_at:string|null;created_at:string}
type Holding={mint:string;amount:number;symbol:string|null;name:string|null;image:string|null;priceUsd:number;valueUsd:number|null}
type Tx={signature:string;slot:number;status:'success'|'failed';memo:string|null;blockTime:number|null;confirmationStatus:string|null;explorerUrl:string}
type WalletData={address:string;balanceSol:number;holdings:Holding[];recent:Tx[];live:boolean;asOf:number;source:string}
const walletRe=/^[1-9A-HJ-NP-Za-km-z]{32,44}$/
const money=(n:number)=>!Number.isFinite(n)?'—':n>=1e6?`$${(n/1e6).toFixed(2)}M`:n>=1e3?`$${(n/1e3).toFixed(1)}K`:`$${n.toFixed(n<1?6:2)}`
const short=(s:string)=>`${s.slice(0,5)}…${s.slice(-5)}`

export default function WalletsPage(){
  const supabase=useMemo(()=>{try{return createClient()}catch{return null}},[])
  const [uid,setUid]=useState(''),[saved,setSaved]=useState<Saved[]>([]),[selected,setSelected]=useState(''),[address,setAddress]=useState(''),[label,setLabel]=useState(''),[data,setData]=useState<WalletData|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const loadSaved=useCallback(async()=>{if(!supabase)return;try{const user=await ensurePaperUser(supabase);setUid(user.id);const {data,error}=await supabase.from('tracked_wallets').select('id,user_id,address,label,notes,is_favorite,tags,alert_on_activity,last_seen_signature,last_activity_at,created_at').eq('user_id',user.id).order('is_favorite',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;setSaved((data||[]) as Saved[])}catch(e){setError(e instanceof Error?e.message:'Wallet tracker unavailable')}},[supabase])
  const inspect=useCallback(async(addr:string)=>{if(!walletRe.test(addr))return;setSelected(addr);setLoading(true);setError('');try{const r=await fetch(`/api/wallet/solana/${encodeURIComponent(addr)}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||`Wallet lookup ${r.status}`);setData(j as WalletData);const row=saved.find(w=>w.address===addr),latest=(j as WalletData).recent?.[0];if(supabase&&row&&latest?.signature&&latest.signature!==row.last_seen_signature){if(row.alert_on_activity&&row.last_seen_signature){setNotice(`${row.label} has new on-chain activity.`);if(typeof Notification!=='undefined'&&Notification.permission==='granted')new Notification('PAPER smart-wallet alert',{body:row.label+' has new on-chain activity.',tag:'paper-wallet-'+row.id})}await supabase.from('tracked_wallets').update({last_seen_signature:latest.signature,last_activity_at:latest.blockTime?new Date(latest.blockTime*1000).toISOString():new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',row.id);void loadSaved()}}catch(e){setData(null);setError(e instanceof Error?e.message:'Wallet lookup failed')}finally{setLoading(false)}},[saved,supabase,loadSaved])
  useEffect(()=>{void loadSaved()},[loadSaved])
  useEffect(()=>{if(!selected)return;void inspect(selected);const id=window.setInterval(()=>{if(!document.hidden)void inspect(selected)},15000);return()=>clearInterval(id)},[selected,inspect])
  async function add(e:FormEvent){e.preventDefault();const a=address.trim();if(!walletRe.test(a)){setError('Enter a valid Solana wallet address.');return}if(!supabase||!uid)return;try{const row={user_id:uid,address:a,label:label.trim()||`Wallet ${short(a)}`};const {error}=await supabase.from('tracked_wallets').upsert(row,{onConflict:'user_id,address'});if(error)throw error;setAddress('');setLabel('');await loadSaved();void inspect(a)}catch(e2){setError(e2 instanceof Error?e2.message:'Could not track wallet')}}
  async function favorite(row:Saved){if(!supabase)return;const {error}=await supabase.from('tracked_wallets').update({is_favorite:!row.is_favorite,updated_at:new Date().toISOString()}).eq('id',row.id);if(error)setError(error.message);else void loadSaved()}
  async function remove(row:Saved){if(!supabase)return;const {error}=await supabase.from('tracked_wallets').delete().eq('id',row.id);if(error)setError(error.message);else{if(selected===row.address){setSelected('');setData(null)}void loadSaved()}}
  async function toggleActivity(row:Saved){if(!supabase)return;let enabled=!row.alert_on_activity;if(enabled&&typeof Notification!=='undefined'&&Notification.permission!=='granted'){const p=await Notification.requestPermission();enabled=p==='granted'}const {error}=await supabase.from('tracked_wallets').update({alert_on_activity:enabled,updated_at:new Date().toISOString()}).eq('id',row.id);if(error)setError(error.message);else void loadSaved()}
  async function setTag(row:Saved,tag:string){if(!supabase)return;const tags=tag?Array.from(new Set([...(row.tags||[]),tag])).slice(0,6):row.tags||[];const {error}=await supabase.from('tracked_wallets').update({tags,updated_at:new Date().toISOString()}).eq('id',row.id);if(error)setError(error.message);else void loadSaved()}
  async function clearTags(row:Saved){if(!supabase)return;await supabase.from('tracked_wallets').update({tags:[],updated_at:new Date().toISOString()}).eq('id',row.id);void loadSaved()}
  const portfolioValue=(data?.holdings||[]).reduce((s,h)=>s+Number(h.valueUsd||0),0),successfulTx=(data?.recent||[]).filter(t=>t.status==='success').length,txSuccessRate=data?.recent?.length?successfulTx/data.recent.length*100:0,pricedHoldings=(data?.holdings||[]).filter(h=>Number(h.valueUsd||0)>0).sort((a,b)=>Number(b.valueUsd||0)-Number(a.valueUsd||0)),topHolding=pricedHoldings[0],topConcentration=portfolioValue>0&&topHolding?.valueUsd?Number(topHolding.valueUsd)/portfolioValue*100:0,lastActivity=data?.recent?.find(t=>t.blockTime)?.blockTime||0
  return <div className="ax-app"><AppHeader active="wallets"/><main className="terminal-page final-wallet-page"><div className="terminal-page-inner">
    <div className="final-page-hero"><div><div className="terminal-eyebrow">SOLANA WALLET INTELLIGENCE · READ ONLY</div><h1>Wallet Tracker</h1><p className="terminal-lead">Track public Solana addresses, live SOL balance, priced SPL holdings and recent on-chain activity. PAPER never asks this tracker to sign a transaction.</p></div><span className="read-only-badge"><WalletCards size={14}/> READ ONLY</span></div>
    <form className="wallet-add-bar" onSubmit={add}><Search size={15}/><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Paste Solana wallet address…"/><input className="wallet-label-input" value={label} onChange={e=>setLabel(e.target.value)} placeholder="Label (optional)"/><button type="submit">Track & inspect</button></form>{error&&<div className="error-card">{error}</div>}{notice&&<div className="terminal-toast">{notice}</div>}
    <section className="wallet-layout"><aside className="tracked-wallet-list"><div className="panel-title"><b>TRACKED WALLETS</b><span>{saved.length}</span></div>{!saved.length&&<div className="portfolio-empty">No wallets tracked yet.</div>}{saved.map(w=><div className={`tracked-wallet-row smart ${selected===w.address?'active':''}`} key={w.id}><button onClick={()=>void inspect(w.address)}><b>{w.label}</b><span>{short(w.address)}</span>{w.tags?.length>0&&<small>{w.tags.join(' · ')}</small>}</button><button className={w.alert_on_activity?'starred':''} onClick={()=>void toggleActivity(w)} title="Activity alert">●</button><button className={w.is_favorite?'starred':''} onClick={()=>void favorite(w)} title="Favorite"><Star size={13} fill={w.is_favorite?'currentColor':'none'}/></button><button onClick={()=>void remove(w)} title="Remove"><Trash2 size={13}/></button></div>)}</aside>
      <div className="wallet-intel-main">{!selected?<div className="wallet-empty-state"><WalletCards size={28}/><b>Select or track a wallet</b><span>Public-chain data only. No wallet connection required.</span></div>:loading&&!data?<div className="wallet-empty-state">Loading mainnet wallet data…</div>:data&&<><section className="wallet-summary"><div><small>WALLET</small><b>{short(data.address)}</b><a href={`https://solscan.io/account/${data.address}`} target="_blank" rel="noreferrer">Solscan <ExternalLink size={11}/></a></div><div><small>SOL BALANCE</small><b>{data.balanceSol.toLocaleString(undefined,{maximumFractionDigits:5})} SOL</b></div><div><small>PRICED TOKEN VALUE</small><b>{money(portfolioValue)}</b><span>DexScreener-priced holdings only</span></div><div><small>RECENT TX SUCCESS</small><b>{data.recent.length?`${txSuccessRate.toFixed(0)}%`:'—'}</b><span>{data.recent.length} sampled signatures</span></div><div><small>TOP HOLDING SHARE</small><b>{topHolding?`${topConcentration.toFixed(1)}%`:'—'}</b><span>{topHolding?.symbol?`${topHolding.symbol}`:'priced holdings only'}</span></div><div><small>LAST ACTIVITY</small><b>{lastActivity?new Date(lastActivity*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'}</b><span>{lastActivity?new Date(lastActivity*1000).toLocaleDateString():''}</span></div><button onClick={()=>void inspect(data.address)} disabled={loading}><RefreshCw size={13}/>{loading?'Refreshing…':'Refresh'}</button></section>
        {selected&&saved.find(w=>w.address===selected)&&<section className="wallet-smart-controls"><div className="panel-title"><b>SMART WALLET TAGS</b><span>Alerts run while PAPER is open</span></div><div className="wallet-tag-row">{['smart money','dev','sniper','whale','watch'].map(tag=><button key={tag} onClick={()=>void setTag(saved.find(w=>w.address===selected)!,tag)}>{tag}</button>)}<button onClick={()=>void clearTags(saved.find(w=>w.address===selected)!)}>clear</button></div></section>}
        <section className="wallet-panel"><div className="panel-title"><b>SPL TOKEN HOLDINGS</b><span>{data.holdings.length} non-zero</span></div><div className="wallet-holding-head"><span>Token</span><span>Amount</span><span>Price</span><span>Priced value</span><span>Mint</span></div>{!data.holdings.length?<div className="portfolio-empty">No standard SPL token balances returned.</div>:data.holdings.slice(0,40).map(h=><Link href={`/spot?mint=${h.mint}`} className="wallet-holding-row" key={h.mint}><span className="portfolio-token">{h.image?<img src={h.image} alt=""/>:<i>{(h.symbol||'??').slice(0,2)}</i>}<b>${h.symbol||short(h.mint)}</b><small>{h.name||''}</small></span><span>{h.amount.toLocaleString(undefined,{maximumFractionDigits:4})}</span><span>{h.priceUsd?money(h.priceUsd):'—'}</span><strong>{h.valueUsd!==null?money(h.valueUsd):'Unpriced'}</strong><span>{short(h.mint)}</span></Link>)}</section>
        <section className="wallet-panel"><div className="panel-title"><b>RECENT ON-CHAIN ACTIVITY</b><span>latest {data.recent.length}</span></div>{!data.recent.length?<div className="portfolio-empty">No recent signatures returned.</div>:data.recent.map(tx=><a className="wallet-tx-row" href={tx.explorerUrl} target="_blank" rel="noreferrer" key={tx.signature}><span className={tx.status==='success'?'gain':'loss'}>{tx.status.toUpperCase()}</span><b>{short(tx.signature)}</b><span>{tx.blockTime?new Date(tx.blockTime*1000).toLocaleString():'Pending time'}</span><span>slot {tx.slot.toLocaleString()}</span><ExternalLink size={12}/></a>)}</section><div className="terminal-source"><i/> LIVE · {data.source} · read-only public chain data · token pricing is best-effort market enrichment</div></>}</div>
    </section>
  </div></main><BottomDock active="wallets"/></div>
}
