'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { Bell, ExternalLink, Plus, Save, Star, Trash2 } from 'lucide-react'
import AppHeader from '@/components/AppHeader'
import BottomDock from '@/components/BottomDock'
import { createClient } from '@/lib/supabase/client'
import { ensurePaperUser } from '@/lib/paper-session'
import type { MarketToken } from '@/lib/types'

type Chain='solana'|'base'|'ethereum'
type Item={id:string;user_id:string;chain_id:Chain;address:string;symbol:string|null;name:string|null;image_url:string|null;alert_above_usd:number|null;alert_below_usd:number|null;created_at:string}
const money=(n:number)=>!Number.isFinite(n)?'—':n>=1e6?`$${(n/1e6).toFixed(2)}M`:n>=1e3?`$${(n/1e3).toFixed(1)}K`:`$${n.toFixed(n<1?8:2)}`
const short=(s:string)=>`${s.slice(0,6)}…${s.slice(-5)}`
const sol=/^[1-9A-HJ-NP-Za-km-z]{32,44}$/,evm=/^0x[a-fA-F0-9]{40}$/

export default function WatchlistPage(){
  const supabase=useMemo(()=>{try{return createClient()}catch{return null}},[])
  const [items,setItems]=useState<Item[]>([]),[live,setLive]=useState<Record<string,MarketToken>>({}),[drafts,setDrafts]=useState<Record<string,{above:string;below:string}>>({}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[addChain,setAddChain]=useState<Chain>('solana'),[addAddress,setAddAddress]=useState(''),[adding,setAdding]=useState(false)
  const load=useCallback(async()=>{if(!supabase)return;try{const user=await ensurePaperUser(supabase),{data,error}=await supabase.from('token_watchlist').select('id,user_id,chain_id,address,symbol,name,image_url,alert_above_usd,alert_below_usd,created_at').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;const rows=(data||[]) as Item[];setItems(rows);setDrafts(cur=>{const next={...cur};for(const row of rows)if(!next[row.id])next[row.id]={above:row.alert_above_usd==null?'':String(row.alert_above_usd),below:row.alert_below_usd==null?'':String(row.alert_below_usd)};return next});const results=await Promise.all(rows.slice(0,40).map(async row=>{const url=row.chain_id==='solana'?`/api/market/token/${encodeURIComponent(row.address)}`:`/api/market/chain/${row.chain_id}/token/${encodeURIComponent(row.address)}`;try{const r=await fetch(url,{cache:'no-store'}),j=await r.json();return r.ok&&j.token?[`${row.chain_id}:${row.address.toLowerCase()}`,j.token as MarketToken] as const:null}catch{return null}}));const map:Record<string,MarketToken>={};for(const result of results)if(result)map[result[0]]=result[1];setLive(map);setError('')}catch(e){setError(e instanceof Error?e.message:'Watchlist unavailable')}finally{setLoading(false)}},[supabase])
  useEffect(()=>{void load();const id=window.setInterval(()=>{if(!document.hidden)void load()},12000);return()=>clearInterval(id)},[load])
  async function add(e:FormEvent){e.preventDefault();if(!supabase)return;const address=addAddress.trim();if(addChain==='solana'?!sol.test(address):!evm.test(address)){setError(addChain==='solana'?'Enter a valid Solana mint.':'Enter a valid 0x token contract.');return}setAdding(true);setError('');try{const user=await ensurePaperUser(supabase),url=addChain==='solana'?`/api/market/token/${encodeURIComponent(address)}`:`/api/market/chain/${addChain}/token/${encodeURIComponent(address)}`,r=await fetch(url,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.token)throw new Error(j.error||'No active market found for that token.');const token=j.token as MarketToken,{error}=await supabase.from('token_watchlist').upsert({user_id:user.id,chain_id:addChain,address:token.mint,symbol:token.symbol,name:token.name,image_url:token.image||null},{onConflict:'user_id,chain_id,address'});if(error)throw error;setAddAddress('');await load()}catch(err){setError(err instanceof Error?err.message:'Could not add token')}finally{setAdding(false)}}
  async function save(row:Item){if(!supabase)return;const d=drafts[row.id]||{above:'',below:''},above=d.above.trim()===''?null:Number(d.above),below=d.below.trim()===''?null:Number(d.below);if((above!==null&&!Number.isFinite(above))||(below!==null&&!Number.isFinite(below))){setError('Alert prices must be valid numbers.');return}const {error}=await supabase.from('token_watchlist').update({alert_above_usd:above,alert_below_usd:below,updated_at:new Date().toISOString()}).eq('id',row.id);if(error)setError(error.message);else void load()}
  async function remove(row:Item){if(!supabase)return;const {error}=await supabase.from('token_watchlist').delete().eq('id',row.id);if(error)setError(error.message);else void load()}
  return <div className="ax-app"><AppHeader active="watchlist"/><main className="terminal-page watchlist-page"><div className="terminal-page-inner">
    <div className="final-page-hero"><div><div className="terminal-eyebrow">TOKEN WATCHLIST · IN-APP PRICE ALERTS</div><h1>Watchlist</h1><p className="terminal-lead">Track Solana, Base and Ethereum tokens with live price checks. Alert states update while PAPER is open; background push notifications are not enabled.</p></div><Link className="watchlist-link" href="/chains"><Star size={14}/> Find Base/ETH tokens</Link></div>
    <form className="watchlist-add" onSubmit={add}><select value={addChain} onChange={e=>setAddChain(e.target.value as Chain)}><option value="solana">Solana</option><option value="base">Base</option><option value="ethereum">Ethereum</option></select><input value={addAddress} onChange={e=>setAddAddress(e.target.value)} placeholder={addChain==='solana'?'Paste Solana token mint…':'Paste 0x token contract…'}/><button disabled={adding}><Plus size={13}/>{adding?'Checking…':'Add token'}</button></form>{error&&<div className="error-card">{error}</div>}
    <section className="watchlist-table"><div className="watchlist-head"><span>Token</span><span>Chain</span><span>Live Price</span><span>5m</span><span>Alert above</span><span>Alert below</span><span>Status</span><span>Actions</span></div>{loading&&!items.length&&<div className="portfolio-empty">Loading watchlist…</div>}{!loading&&!items.length&&<div className="portfolio-empty">Your watchlist is empty. Add a token mint/contract above or use the Chains market browser.</div>}{items.map(row=>{const key=`${row.chain_id}:${row.address.toLowerCase()}`,token=live[key],price=Number(token?.priceUsd||0),above=row.alert_above_usd==null?null:Number(row.alert_above_usd),below=row.alert_below_usd==null?null:Number(row.alert_below_usd),trigger=price>0&&((above!==null&&price>=above)||(below!==null&&price<=below)),d=drafts[row.id]||{above:'',below:''},href=row.chain_id==='solana'?`/spot?mint=${row.address}`:token?.pairUrl||token?.buyUrl||'#';return <div className={`watchlist-row ${trigger?'triggered':''}`} key={row.id}><Link href={href} target={row.chain_id==='solana'?undefined:'_blank'} className="watch-token"><span className="pair-avatar-terminal">{token?.image||row.image_url?<img src={token?.image||row.image_url||''} alt=""/>:<b>{(token?.symbol||row.symbol||'??').slice(0,2)}</b>}</span><span><b>${token?.symbol||row.symbol||'TOKEN'}</b><small>{token?.name||row.name||short(row.address)}</small></span>{row.chain_id!=='solana'&&<ExternalLink size={11}/>}</Link><span className={`chain-pill ${row.chain_id}`}>{row.chain_id==='ethereum'?'ETH':row.chain_id.toUpperCase()}</span><strong>{price?money(price):'Unavailable'}</strong><strong className={Number(token?.priceChange5m||0)>=0?'gain':'loss'}>{token?`${Number(token.priceChange5m||0)>=0?'+':''}${Number(token.priceChange5m||0).toFixed(2)}%`:'—'}</strong><input type="number" step="any" placeholder="—" value={d.above} onChange={e=>setDrafts(cur=>({...cur,[row.id]:{...d,above:e.target.value}}))}/><input type="number" step="any" placeholder="—" value={d.below} onChange={e=>setDrafts(cur=>({...cur,[row.id]:{...d,below:e.target.value}}))}/><span className={trigger?'watch-alert hot':'watch-alert'}><Bell size={12}/>{trigger?'TRIGGERED':above!==null||below!==null?'ARMED':'NO ALERT'}</span><span className="watch-actions"><button onClick={()=>void save(row)} title="Save alert"><Save size={13}/></button><button onClick={()=>void remove(row)} title="Remove"><Trash2 size={13}/></button></span></div>})}</section><div className="chain-paper-note"><b>Alert behavior:</b> thresholds are stored in your PAPER account. They are evaluated by this page against live market lookups while the app is open; they do not send background email, SMS, or push notifications.</div>
  </div></main><BottomDock active="watchlist"/></div>
}
