'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import AppHeader from '@/components/AppHeader'
import BottomDock from '@/components/BottomDock'
import { createClient } from '@/lib/supabase/client'
import { ensurePaperUser } from '@/lib/paper-session'

type Profile={username:string|null;display_name:string|null;bio:string|null;x_handle:string|null;avatar_url:string|null;avatar_emoji:string|null;accent:string|null}
type Account={cash_usd:number;starting_balance_usd:number;status:string}
type Visibility={public_profile:boolean;leaderboard_opt_out:boolean;activity_public:boolean;share_pnl:boolean}
const avatars=['🪙','🦍','🐸','🐕','🐈','🦊','🧠','🚀','👾','🦄','🐻','🐂'],accents=['violet','blue','cyan','rose','amber','lime'],blocked=/(nigg|fagg|kike|spic|chink|wetback|tranny|retard)/i

export default function ProfilePage(){
  const [profile,setProfile]=useState<Profile|null>(null),[account,setAccount]=useState<Account|null>(null),[userId,setUserId]=useState(''),[recoveryEmail,setRecoveryEmail]=useState(''),[username,setUsername]=useState(''),[displayName,setDisplayName]=useState(''),[bio,setBio]=useState(''),[xHandle,setXHandle]=useState(''),[avatar,setAvatar]=useState('🪙'),[avatarUrl,setAvatarUrl]=useState<string|null>(null),[accent,setAccent]=useState('violet'),[message,setMessage]=useState(''),[recoveryMessage,setRecoveryMessage]=useState(''),[busy,setBusy]=useState(true),[uploading,setUploading]=useState(false)
  const supabase=useMemo(()=>{try{return createClient()}catch{return null}},[])
  const [uiPrefs,setUiPrefs]=useState<{density:'comfortable'|'compact';fontScale:number}>({density:'comfortable',fontScale:1})
  useEffect(()=>{const start=window.setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem('paper.ui.preferences')||'{}');setUiPrefs({density:saved.density==='compact'?'compact':'comfortable',fontScale:[.9,1,1.1].includes(Number(saved.fontScale))?Number(saved.fontScale):1})}catch{}},0);return()=>clearTimeout(start)},[])
  function saveUi(next:{density:'comfortable'|'compact';fontScale:number}){setUiPrefs(next);localStorage.setItem('paper.ui.preferences',JSON.stringify(next));window.dispatchEvent(new Event('paper:ui-preferences'))}

  useEffect(()=>{if(!supabase)return;let alive=true;const start=window.setTimeout(()=>void(async()=>{try{const user=await ensurePaperUser(supabase);if(!alive)return;setUserId(user.id);setRecoveryEmail(user.email||'');const [{data,error},{data:acct,error:acctError}]=await Promise.all([supabase.from('profiles').select('username,display_name,bio,x_handle,avatar_url,avatar_emoji,accent').eq('id',user.id).single(),supabase.from('paper_accounts').select('cash_usd,starting_balance_usd,status').eq('user_id',user.id).single()]);if(error)throw error;if(acctError)throw acctError;if(data&&alive){const p=data as Profile;setProfile(p);setUsername(p.username||'');setDisplayName(p.display_name||'Paper Trader');setBio(p.bio||'');setXHandle(p.x_handle||'');setAvatar(p.avatar_emoji||'🪙');setAvatarUrl(p.avatar_url||null);setAccent(p.accent||'violet')}if(alive)setAccount(acct as Account)}catch(e){if(alive)setMessage(e instanceof Error?e.message:'Profile unavailable')}finally{if(alive)setBusy(false)}})(),0);return()=>{alive=false;clearTimeout(start)}},[supabase])

  async function uploadProfilePicture(file?:File){if(!file||!supabase||!userId)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setMessage('Use a PNG, JPG, or WebP image.');return}if(file.size>2_000_000){setMessage('PFP must be under 2 MB.');return}setUploading(true);setMessage('');try{const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg',path=`${userId}/avatar.${ext}`,{error}=await supabase.storage.from('avatars').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(error)throw error;const {data}=supabase.storage.from('avatars').getPublicUrl(path),url=`${data.publicUrl}?v=${Date.now()}`,{error:updateError}=await supabase.from('profiles').update({avatar_url:url,updated_at:new Date().toISOString()}).eq('id',userId);if(updateError)throw updateError;setAvatarUrl(url);setMessage('Profile picture updated.')}catch(e){setMessage(e instanceof Error?e.message:'PFP upload failed')}finally{setUploading(false)}}

  async function save(e:FormEvent){e.preventDefault();if(!supabase||!userId)return;const cleanUser=username.trim(),cleanDisplay=displayName.trim(),cleanBio=bio.trim();if(!/^[A-Za-z0-9_]{3,24}$/.test(cleanUser)){setMessage('Username must be 3–24 characters using letters, numbers, or underscores.');return}if(!cleanDisplay||cleanDisplay.length>40){setMessage('Display name must be 1–40 characters.');return}if(cleanBio.length>160){setMessage('Bio must be 160 characters or less.');return}if(blocked.test(`${cleanUser} ${cleanDisplay} ${cleanBio}`)){setMessage('Please choose different profile text.');return}setMessage('Saving…');const {error}=await supabase.from('profiles').update({username:cleanUser,display_name:cleanDisplay,bio:cleanBio||null,x_handle:xHandle.trim()||null,avatar_emoji:avatar,accent,updated_at:new Date().toISOString()}).eq('id',userId);if(error){setMessage(error.message);return}setProfile(p=>p?{...p,username:cleanUser,display_name:cleanDisplay,bio:cleanBio,x_handle:xHandle.trim(),avatar_emoji:avatar,accent}:p);setMessage('Profile saved.');window.dispatchEvent(new Event('paper:account-changed'))}
  async function addRecoveryEmail(){if(!supabase)return;const email=recoveryEmail.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email)){setRecoveryMessage('Enter a valid email.');return}setRecoveryMessage('Sending verification…');const {error}=await supabase.auth.updateUser({email});setRecoveryMessage(error?error.message:'Check your email to verify it. Your PAPER history stays on this account.')}
  const cash=Number(account?.cash_usd||0)
  return <div className="ax-app"><AppHeader active="profile"/><main className="terminal-page"><div className="terminal-page-inner"><div className="terminal-eyebrow">PAPER TRADER PROFILE</div><h1>Your trading identity.</h1><p className="terminal-lead">Customize how you appear across the PAPER-only beta. No trading wallet, funded account, custody connection, or payout address is requested.</p>{busy?<div className="empty-card">Loading your PAPER profile…</div>:!profile||!account?<div className="error-card">{message||'Profile unavailable.'}</div>:<>
    <form className="profile-card" onSubmit={save}><div className="profile-preview"><div className={`preview-avatar accent-${accent}`}>{avatarUrl?<img src={avatarUrl} alt="Profile"/>:avatar}</div><div><strong>{displayName||'Paper Trader'}</strong><div className="muted-small">@{username||'paper_trader'}</div><div className="muted-small">${cash.toFixed(2)} PAPER SOL</div></div></div><label className="profile-pfp-upload">Profile picture<input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={e=>void uploadProfilePicture(e.target.files?.[0])}/><span>{uploading?'Uploading…':'Upload PNG/JPG/WebP · max 2 MB'}</span></label><div className="profile-grid"><label>Username<input value={username} maxLength={24} onChange={e=>setUsername(e.target.value.replace(/\s+/g,'_'))}/></label><label>Display name<input value={displayName} maxLength={40} onChange={e=>setDisplayName(e.target.value)}/></label><label style={{gridColumn:'1 / -1'}}>Bio<textarea value={bio} maxLength={160} placeholder="Memecoin trader. PAPER P&L only." onChange={e=>setBio(e.target.value)}/></label><label>X handle (optional)<input value={xHandle} maxLength={32} placeholder="@handle" onChange={e=>setXHandle(e.target.value)}/></label><label>PAPER buying power<input value={`${cash.toFixed(2)} PAPER SOL`} disabled/></label></div><label style={{marginTop:16}}>Default avatar</label><div className="avatar-picker">{avatars.map(v=><button type="button" key={v} className={avatar===v?'avatar-choice selected':'avatar-choice'} onClick={()=>setAvatar(v)}>{v}</button>)}</div><label>Accent</label><div className="accent-picker">{accents.map(v=><button type="button" aria-label={`${v} accent`} key={v} className={`accent-choice accent-${v} ${accent===v?'selected':''}`} onClick={()=>setAccent(v)}/>)}</div><button className="profile-save" type="submit">SAVE PROFILE</button>{message&&<div className="profile-message">{message}</div>}</form>
    <section className="account-panel"><div className="terminal-eyebrow">ACCOUNT RECOVERY</div><h3>Protect your PAPER history</h3><p>If you clear browser data or switch devices before linking recovery, this anonymous PAPER account cannot be restored. Adding an email is optional for account recovery in the PAPER-only beta.</p><div className="inline-action"><input type="email" value={recoveryEmail} placeholder="you@example.com" onChange={e=>setRecoveryEmail(e.target.value)}/><button onClick={()=>void addRecoveryEmail()}>ADD RECOVERY EMAIL</button></div>{recoveryMessage&&<div className="profile-message">{recoveryMessage}</div>}</section>
    <section className="account-panel"><div className="terminal-eyebrow">TERMINAL DISPLAY</div><h3>Make PAPER fit your screen.</h3><p>Your display preferences are saved in this browser and applied across the terminal.</p><div className="ui-pref-grid"><div><small>DENSITY</small><button className={uiPrefs.density==='comfortable'?'active':''} onClick={()=>saveUi({...uiPrefs,density:'comfortable'})}>Comfortable</button><button className={uiPrefs.density==='compact'?'active':''} onClick={()=>saveUi({...uiPrefs,density:'compact'})}>Compact</button></div><div><small>FONT SCALE</small>{[[.9,'90%'],[1,'100%'],[1.1,'110%']].map(([value,label])=><button key={String(value)} className={uiPrefs.fontScale===value?'active':''} onClick={()=>saveUi({...uiPrefs,fontScale:Number(value)})}>{label}</button>)}</div></div></section>
  </>}</div></main><BottomDock active="profile"/></div>
}
