create table if not exists public.portfolio_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  equity_usd numeric(20,8) not null check (equity_usd >= 0),
  cash_usd numeric(20,8) not null check (cash_usd >= 0),
  open_value_usd numeric(20,8) not null check (open_value_usd >= 0),
  realized_pnl_usd numeric(20,8) not null,
  unrealized_pnl_usd numeric(20,8) not null,
  created_at timestamptz not null default now()
);

create index if not exists portfolio_snapshots_user_created_idx
  on public.portfolio_snapshots(user_id, created_at desc);

alter table public.portfolio_snapshots enable row level security;

drop policy if exists portfolio_snapshots_select_own on public.portfolio_snapshots;
create policy portfolio_snapshots_select_own
  on public.portfolio_snapshots
  for select to authenticated
  using (auth.uid() = user_id);

create or replace function public.record_portfolio_snapshot(
  p_equity_usd numeric,
  p_cash_usd numeric,
  p_open_value_usd numeric,
  p_realized_pnl_usd numeric,
  p_unrealized_pnl_usd numeric
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_last timestamptz;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  if p_equity_usd is null or p_cash_usd is null or p_open_value_usd is null then raise exception 'Snapshot values are required'; end if;
  if p_equity_usd < 0 or p_cash_usd < 0 or p_open_value_usd < 0 then raise exception 'Snapshot values must be non-negative'; end if;

  select created_at into v_last
  from public.portfolio_snapshots
  where user_id = v_uid
  order by created_at desc
  limit 1;

  if v_last is not null and v_last > now() - interval '60 seconds' then return; end if;

  insert into public.portfolio_snapshots(user_id,equity_usd,cash_usd,open_value_usd,realized_pnl_usd,unrealized_pnl_usd)
  values(v_uid,p_equity_usd,p_cash_usd,p_open_value_usd,p_realized_pnl_usd,p_unrealized_pnl_usd);
end;
$$;

revoke all on function public.record_portfolio_snapshot(numeric,numeric,numeric,numeric,numeric) from public;
grant execute on function public.record_portfolio_snapshot(numeric,numeric,numeric,numeric,numeric) to authenticated;
grant select on public.portfolio_snapshots to authenticated;
